---
version: '3'
services:
  web:
    build: web/.
    container_name: web
    ports:
      - "8082:8082"
    network_mode: host
  nginx:
    build: nginx/.
    container_name: nginx
    ports:
      - "8083:8083"
    links:
      - web
    
